### ISSUE TITLE
TODO before release

### ISSUE THREAD

**Issue by targos** [mljs/random-forest#4]
- [x] Replace `ml-stat` with `ml-array-mean` and `ml-array-median` (to be created in https://github.com/mljs/array)
- [x] Refactor [ml-cart](https://github.com/mljs/decision-tree-cart) to ES module and use it
- [x] Check and optimize the use of the Matrix package

**Comment by jajoe** [comment]
I'm not sure than the separation into two classes is a good idea. When we will have to add features (like subsampling or pruning for example) it could be easier to have the same base. If there are two classes, we will have to modify both classes to add features.

**Comment by targos** [comment]
This way of programming (having a base class to implement common code) is very Java-ish. In JS, we have the liberty to implement methods in functions that are not directly defined in the class. One of the advantages of this approach is that you can use separate files to write the different methods. It's true that we have to modify both classes, but it would be just to add 3 or 4 lines to call the common method.

**Comment by 0x33467** [comment]
but it's a little bit weird to pass always the classifier to each method that is common to both classes (if we only use functions), I mean, it looks better with a base class, no? @targos

**Comment by targos** [comment]
It's a refactoring I would like to do myself but it's not needed for the release. I removed it from the list.

**Comment by maasencioh** [comment]
Even I think that we could check a little bit more the API, the code was published in bc09bab3f2f252a61efd33885649a14fd96f7098 and the list was fulfilled, so I'm closing this
